### ISSUE TITLE
Is there a way to select voltage reading from FC or PDB ?

### ISSUE THREAD

**Issue by Burnarz** [flyinglemonfpv/FLOSD_CF#1]
Hi, 
First of all, thanks for this great PDB ;)
I just flashed mine to v2.1, but i will switch to Kiss FC, and then couldn't get voltage reading from FC right ?
So, i was wondering if you could add to ability to select voltage reading from FC or PDB.
Or even provide me the old firmware version.
Thanx

**Comment by Burnarz** [comment]
Would be great if voltage reading was set to PDB by default.
So it will be autonmous, and the one interesseted in voltage reading from FC could switch as they have the link with FC.

**Comment by flyinglemonfpv** [comment]
For this moment it's not possible to switch between FC and PDB. But this is good idea. We will add this function in next release.

**Comment by Burnarz** [comment]
Thanks for your quick answer.
Where can i found the old firmware, so i can have voltage from PDB, please

**Comment by Burnarz** [comment]
Nevermind didn't saw you've add it.
Thanks, can't wait for new release then :D
