### ISSUE TITLE
Is it compatible with MWOSD ?

### ISSUE THREAD

**Issue by Burnarz** [flyinglemonfpv/FLOSD_CF#2]
Hi, me again ;)
Is the board compatible with MWOSD (or any other) or should we stay with your Firmware ?

Thanks in advance.

**Comment by Burnarz** [comment]
Got the answer.
"Yes it is."

Hope it helps ;)

**Comment by jasiucytrynowy** [comment]
No it isn't. It's only compatible with our firmware.
