### ISSUE TITLE
Unable to enter Stick menu using frsky x4r running SBUS

### ISSUE THREAD

**Issue by cptquad** [flyinglemonfpv/FLOSD_CF#3]

**Comment by cptquad** [comment]
I am unable to enter the onscreen menu using the stick combinations, Tried all HEX files and combinations. 

PC connection also fails when using version 2.1.2. PC connection works with version 1.5

Specs:
Dodo Flight Controller
Frsky Taranis
Frsky X4RII running SBUS

**Comment by mischkaaa** [comment]
DONE WITH v2.1.2
